# Generated by Django 5.2.4 on 2025-08-01 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_alter_women_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create']},
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_9f33c2_idx',
        ),
        migrations.AlterField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='women.category'),
        ),
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='women.tagpost'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['time_create'], name='women_women_time_cr_21b781_idx'),
        ),
    ]
